version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  validate:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1.1-dependencies-{{ checksum "package-lock.json" }}'
            - v1.1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1.1-dependencies-{{ checksum "package-lock.json" }}'
      - run: npm run lint
      - run: npm test
workflows:
  node-tests:
    jobs:
      - validate
